import express from "express";
import cors from "cors";

const app = express();
app.use(cors());

const customerDetails = [
  {
    id: 1,
    Name: "Alexander",
    Country: "Brazil",
    Region: "South America",
    Active: "true",
    PaymentType: "Alipay",
  },
  {
    id: 2,
    Name: "Olivia",
    Country: "Canada",
    Region: "North America",
    Active: "false",
    PaymentType: "Google Pay",
  },
  {
    id: 3,
    Name: "Liam",
    Country: "Australia",
    Region: "Oceania",
    Active: "true",
    PaymentType: "PayPal",
  },
  {
    id: 4,
    Name: "Sophia",
    Country: "Egypt",
    Region: "North Africa/Middle East",
    Active: "false",
    PaymentType: "Cash App",
  },
  {
    id: 5,
    Name: "Ethan",
    Country: "Japan",
    Region: "East Asia",
    Active: "true",
    PaymentType: "WeChat Pay",
  },
  {
    id: 6,
    Name: "Emma",
    Country: "Greece",
    Region: "Southern Europe",
    Active: "true",
    PaymentType: "Venmo",
  },
  {
    id: 7,
    Name: "Noah",
    Country: "Sweden",
    Region: "Northern Europe",
    Active: "false",
    PaymentType: "Skrill",
  },
  {
    id: 8,
    Name: "Ava",
    Country: "Kenya",
    Region: "East Africa",
    Active: "true",
    PaymentType: "Stripe",
  },
  {
    id: 9,
    Name: "Michael",
    Country: "Argentina",
    Region: "South America",
    Active: "false",
    PaymentType: "Western Union",
  },
  {
    id: 10,
    Name: "Isabella",
    Country: "Russia",
    Region: "Eurasia",
    Active: "true",
    PaymentType: "Apple Pay",
  },
  {
    id: 11,
    Name: "Benjamin",
    Country: "Vietnam",
    Region: "Southeast Asia",
    Active: "false",
    PaymentType: "Square Cash",
  },
  {
    id: 12,
    Name: "Mia",
    Country: "Norway",
    Region: "Northern Europe",
    Active: "false",
    PaymentType: "Paytm",
  },
  {
    id: 13,
    Name: "James",
    Country: "Mexico",
    Region: "North America",
    Active: "true",
    PaymentType: "NETELLER",
  },
  {
    id: 14,
    Name: "Amelia",
    Country: "India",
    Region: "South Asia",
    Active: "true",
    PaymentType: "Zelle",
  },
  {
    id: 15,
    Name: "William",
    Country: "Spain",
    Region: "Southern Europe",
    Active: "false",
    PaymentType: "Amazon Pay",
  },
  {
    id: 16,
    Name: "Harper",
    Country: "South Korea",
    Region: "East Asia",
    Active: "true",
    PaymentType: "Alipay",
  },
  {
    id: 17,
    Name: "Daniel",
    Country: "Chile",
    Region: "South America",
    Active: "false",
    PaymentType: "Google Pay",
  },
  {
    id: 18,
    Name: "Evelyn",
    Country: "Finland",
    Region: "Northern Europe",
    Active: "false",
    PaymentType: "PayPal",
  },
  {
    id: 19,
    Name: "Matthew",
    Country: "Saudi Arabia",
    Region: "Middle East",
    Active: "true",
    PaymentType: "Cash App",
  },
  {
    id: 20,
    Name: "Abigail",
    Country: "Nigeria",
    Region: "West Africa",
    Active: "true",
    PaymentType: "WeChat Pay",
  },
  {
    id: 21,
    Name: "Joseph",
    Country: "Italy",
    Region: "Southern Europe",
    Active: "false",
    PaymentType: "Venmo",
  },
  {
    id: 22,
    Name: "Emily",
    Country: "Turkey",
    Region: "Middle East",
    Active: "true",
    PaymentType: "Skrill",
  },
  {
    id: 23,
    Name: "Samuel",
    Country: "Thailand",
    Region: "Southeast Asia",
    Active: "false",
    PaymentType: "Stripe",
  },
  {
    id: 24,
    Name: "Elizabeth",
    Country: "Malaysia",
    Region: "Southeast Asia",
    Active: "true",
    PaymentType: "Apple Pay",
  },
  {
    id: 25,
    Name: "David",
    Country: "Germany",
    Region: "Central Europe",
    Active: "false",
    PaymentType: "Square Cash",
  },
  {
    id: 26,
    Name: "Sofia",
    Country: "Peru",
    Region: "South America",
    Active: "true",
    PaymentType: "Paytm",
  },
  {
    id: 27,
    Name: "Benjamin",
    Country: "Morocco",
    Region: "North Africa",
    Active: "false",
    PaymentType: "NETELLER",
  },
  {
    id: 28,
    Name: "Scarlett",
    Country: "Netherlands",
    Region: "Western Europe",
    Active: "false",
    PaymentType: "Zelle",
  },
  {
    id: 29,
    Name: "Jack",
    Country: "Colombia",
    Region: "South America",
    Active: "true",
    PaymentType: "Amazon Pay",
  },
  {
    id: 30,
    Name: "Grace",
    Country: "Singapore",
    Region: "Southeast Asia",
    Active: "false",
    PaymentType: "Cash App",
  },
  {
    id: 31,
    Name: "Henry",
    Country: "Switzerland",
    Region: "Central Europe",
    Active: "true",
    PaymentType: "WeChat Pay",
  },
  {
    id: 32,
    Name: "Victoria",
    Country: "Ireland",
    Region: "Western Europe",
    Active: "false",
    PaymentType: "PayPal",
  },
  {
    id: 33,
    Name: "Daniel",
    Country: "South Africa",
    Region: "Southern Africa",
    Active: "false",
    PaymentType: "Alipay",
  },
  {
    id: 34,
    Name: "Lily",
    Country: "United Arab Emirates",
    Region: "Middle East",
    Active: "true",
    PaymentType: "Google Pay",
  },
  {
    id: 35,
    Name: "Andrew",
    Country: "New Zealand",
    Region: "Oceania",
    Active: "false",
    PaymentType: "PayPal",
  },
  {
    id: 36,
    Name: "Chloe",
    Country: "Israel",
    Region: "Middle East",
    Active: "true",
    PaymentType: "Cash App",
  },
  {
    id: 37,
    Name: "Logan",
    Country: "Denmark",
    Region: "Northern Europe",
    Active: "true",
    PaymentType: "NETELLER",
  },
  {
    id: 38,
    Name: "Natalie",
    Country: "Philippines",
    Region: "Southeast Asia",
    Active: "false",
    PaymentType: "Zelle",
  },
  {
    id: 39,
    Name: "Christopher",
    Country: "Belgium",
    Region: "Western Europe",
    Active: "true",
    PaymentType: "Amazon Pay",
  },
  {
    id: 40,
    Name: "Ella",
    Country: "Portugal",
    Region: "Southern Europe",
    Active: "false",
    PaymentType: "Skrill",
  },
  {
    id: 41,
    Name: "Gabriel",
    Country: "Qatar",
    Region: "Middle East",
    Active: "false",
    PaymentType: "Stripe",
  },
  {
    id: 42,
    Name: "Zoey",
    Country: "Pakistan",
    Region: "South Asia",
    Active: "true",
    PaymentType: "Apple Pay",
  },
  {
    id: 43,
    Name: "Nicholas",
    Country: "Austria",
    Region: "Central Europe",
    Active: "false",
    PaymentType: "Cash App",
  },
  {
    id: 44,
    Name: "Madison",
    Country: "Hungary",
    Region: "Central Europe",
    Active: "true",
    PaymentType: "Square Cash",
  },
  {
    id: 45,
    Name: "Samuel",
    Country: "Czech Republic",
    Region: "Central Europe",
    Active: "false",
    PaymentType: "Paytm",
  },
  {
    id: 46,
    Name: "Aria",
    Country: "Venezuela",
    Region: "South America",
    Active: "true",
    PaymentType: "NETELLER",
  },
  {
    id: 47,
    Name: "Anthony",
    Country: "Bangladesh",
    Region: "South Asia",
    Active: "false",
    PaymentType: "Zelle",
  },
  {
    id: 48,
    Name: "Hannah",
    Country: "Ukraine",
    Region: "Eastern Europe",
    Active: "true",
    PaymentType: "Amazon Pay",
  },
  {
    id: 49,
    Name: "Joshua",
    Country: "Kuwait",
    Region: "Middle East",
    Active: "false",
    PaymentType: "Venmo",
  },
  {
    id: 50,
    Name: "Lillian",
    Country: "Croatia",
    Region: "Southern Europe",
    Active: "false",
    PaymentType: "Square Cash",
  },
  {
    id: 51,
    Name: "Mia",
    Country: "Vietnam",
    Region: "Southeast Asia",
    Active: "true",
    PaymentType: "Zelle",
  },
  {
    id: 52,
    Name: "Benjamin",
    Country: "Netherlands",
    Region: "Western Europe",
    Active: "false",
    PaymentType: "NETELLER",
  },
  {
    id: 53,
    Name: "Emma",
    Country: "Morocco",
    Region: "North Africa",
    Active: "true",
    PaymentType: "Cash App",
  },
  {
    id: 54,
    Name: "Ethan",
    Country: "Philippines",
    Region: "Southeast Asia",
    Active: "false",
    PaymentType: "Venmo",
  },
  {
    id: 55,
    Name: "Olivia",
    Country: "Greece",
    Region: "Southern Europe",
    Active: "true",
    PaymentType: "PayPal",
  },
  {
    id: 56,
    Name: "William",
    Country: "Brazil",
    Region: "South America",
    Active: "true",
    PaymentType: "Alipay",
  },
  {
    id: 57,
    Name: "Sophia",
    Country: "Switzerland",
    Region: "Central Europe",
    Active: "false",
    PaymentType: "WeChat Pay",
  },
  {
    id: 58,
    Name: "Liam",
    Country: "Egypt",
    Region: "North Africa/Middle East",
    Active: "false",
    PaymentType: "Amazon Pay",
  },
  {
    id: 59,
    Name: "Isabella",
    Country: "Russia",
    Region: "Eurasia",
    Active: "true",
    PaymentType: "Apple Pay",
  },
  {
    id: 60,
    Name: "Noah",
    Country: "Nigeria",
    Region: "West Africa",
    Active: "false",
    PaymentType: "Stripe",
  },
  {
    id: 61,
    Name: "Ava",
    Country: "New Zealand",
    Region: "Oceania",
    Active: "true",
    PaymentType: "Venmo",
  },
  {
    id: 62,
    Name: "James",
    Country: "South Africa",
    Region: "Southern Africa",
    Active: "false",
    PaymentType: "Square Cash",
  },
  {
    id: 63,
    Name: "Harper",
    Country: "United Arab Emirates",
    Region: "Middle East",
    Active: "true",
    PaymentType: "NETELLER",
  },
  {
    id: 64,
    Name: "Michael",
    Country: "Chile",
    Region: "South America",
    Active: "false",
    PaymentType: "Bank Transfer",
  },
  {
    id: 65,
    Name: "Sophia",
    Country: "Saudi Arabia",
    Region: "Middle East",
    Active: "true",
    PaymentType: "Stripe",
  },
  {
    id: 66,
    Name: "Daniel",
    Country: "Canada",
    Region: "North America",
    Active: "true",
    PaymentType: "Payoneer",
  },
  {
    id: 67,
    Name: "Olivia",
    Country: "Belgium",
    Region: "Western Europe",
    Active: "false",
    PaymentType: "PayPal",
  },
  {
    id: 68,
    Name: "Alexander",
    Country: "Kenya",
    Region: "East Africa",
    Active: "true",
    PaymentType: "Debit Card",
  },
  {
    id: 69,
    Name: "Mia",
    Country: "Australia",
    Region: "Oceania",
    Active: "false",
    PaymentType: "SEPA Direct Debit",
  },
  {
    id: 70,
    Name: "Ethan",
    Country: "Italy",
    Region: "Southern Europe",
    Active: "true",
    PaymentType: "Venmo",
  },
  {
    id: 71,
    Name: "Olivia",
    Country: "Malaysia",
    Region: "Southeast Asia",
    Active: "false",
    PaymentType: "Alipay",
  },
  {
    id: 72,
    Name: "Benjamin",
    Country: "Germany",
    Region: "Central Europe",
    Active: "false",
    PaymentType: "Square Cash",
  },
  {
    id: 73,
    Name: "Ava",
    Country: "Tunisia",
    Region: "North Africa",
    Active: "true",
    PaymentType: "QuickPay",
  },
  {
    id: 74,
    Name: "Sophia",
    Country: "Argentina",
    Region: "South America",
    Active: "false",
    PaymentType: "Postpaid Account",
  },
  {
    id: 75,
    Name: "Liam",
    Country: "Turkey",
    Region: "Middle East",
    Active: "true",
    PaymentType: "Cashier's Check",
  },
  {
    id: 76,
    Name: "Emma",
    Country: "Japan",
    Region: "East Asia",
    Active: "true",
    PaymentType: "MoneyGram",
  },
  {
    id: 77,
    Name: "Noah",
    Country: "Denmark",
    Region: "Northern Europe",
    Active: "false",
    PaymentType: "Prepaid Card",
  },
  {
    id: 78,
    Name: "Olivia",
    Country: "Qatar",
    Region: "Middle East",
    Active: "false",
    PaymentType: "Klarna",
  },
  {
    id: 79,
    Name: "William",
    Country: "Spain",
    Region: "Southern Europe",
    Active: "true",
    PaymentType: "WebMoney",
  },
  {
    id: 80,
    Name: "Ava",
    Country: "Uganda",
    Region: "East Africa",
    Active: "false",
    PaymentType: "Dwolla",
  },
  {
    id: 81,
    Name: "Olivia",
    Country: "Poland",
    Region: "Eastern Europe",
    Active: "false",
    PaymentType: "ACH Transfer",
  },
  {
    id: 82,
    Name: "Sophia",
    Country: "Ghana",
    Region: "West Africa",
    Active: "true",
    PaymentType: "Revolut",
  },
  {
    id: 83,
    Name: "Ethan",
    Country: "Portugal",
    Region: "Southern Europe",
    Active: "true",
    PaymentType: "Google Wallet",
  },
  {
    id: 84,
    Name: "Mia",
    Country: "Venezuela",
    Region: "South America",
    Active: "false",
    PaymentType: "Afterpay",
  },
  {
    id: 85,
    Name: "Benjamin",
    Country: "South Korea",
    Region: "East Asia",
    Active: "false",
    PaymentType: "Cash App",
  },
  {
    id: 86,
    Name: "Emma",
    Country: "Estonia",
    Region: "Baltic Region",
    Active: "true",
    PaymentType: "Cash",
  },
  {
    id: 87,
    Name: "Olivia",
    Country: "Kuwait",
    Region: "Middle East",
    Active: "false",
    PaymentType: "PayPal",
  },
  {
    id: 88,
    Name: "William",
    Country: "Austria",
    Region: "Central Europe",
    Active: "true",
    PaymentType: "Bank Transfer",
  },
  {
    id: 89,
    Name: "Ava",
    Country: "Slovenia",
    Region: "Central Europe",
    Active: "false",
    PaymentType: "Venmo",
  },
  {
    id: 90,
    Name: "Sophia",
    Country: "Mexico",
    Region: "North America",
    Active: "true",
    PaymentType: "Bitcoin",
  },
  {
    id: 91,
    Name: "Liam",
    Country: "Bangladesh",
    Region: "South Asia",
    Active: "false",
    PaymentType: "Debit Card",
  },
  {
    id: 92,
    Name: "Emma",
    Country: "Sweden",
    Region: "Northern Europe",
    Active: "true",
    PaymentType: "Stripe",
  },
  {
    id: 93,
    Name: "Noah",
    Country: "Ireland",
    Region: "Western Europe",
    Active: "false",
    PaymentType: "Western Union",
  },
  {
    id: 94,
    Name: "Olivia",
    Country: "Peru",
    Region: "South America",
    Active: "true",
    PaymentType: "Money Order",
  },
  {
    id: 95,
    Name: "Benjamin",
    Country: "Czech Republic",
    Region: "Central Europe",
    Active: "false",
    PaymentType: "Square Cash",
  },
  {
    id: 96,
    Name: "Lillian",
    Country: "Croatia",
    Region: "Southern Europe",
    Active: "false",
    PaymentType: "PayPal",
  },
  {
    id: 97,
    Name: "Caleb",
    Country: "Oman",
    Region: "Middle East",
    Active: "true",
    PaymentType: "Cash App",
  },
  {
    id: 98,
    Name: "Addison",
    Country: "Sri Lanka",
    Region: "South Asia",
    Active: "true",
    PaymentType: "Google Pay",
  },
  {
    id: 99,
    Name: "Luke",
    Country: "Ghana",
    Region: "West Africa",
    Active: "false",
    PaymentType: "Venmo",
  },
  {
    id: 100,
    Name: "Lily",
    Country: "Ukraine",
    Region: "Eastern Europe",
    Active: "false",
    PaymentType: "PayPal",
  },
];

app.get("/getData", (req, res) => {
  res.send(customerDetails);
});

app.listen(5001, () => console.log("app is running"));
